# -*- coding: utf-8 -*-
"""Decision_Tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1abQeuLOEJys8ssl9fIx4ZKfJreWlw_Fi
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

url =  "data_arrhythmia.csv"
df = pd.read_csv(url, delimiter=';')
df_columns = df.iloc[:, 0:281]
df = df_columns.apply(lambda x: pd.to_numeric(x, errors='coerce'))
df.dropna(inplace=True)
df

X = df.drop('diagnosis',axis=1)
Y = df.diagnosis

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=1)

dt = DecisionTreeClassifier(random_state=1)

dt.fit(X_train,Y_train)

Y_pred = dt.predict(X_test)

print('Akurasi:',accuracy_score(Y_test,Y_pred))

import warnings
from sklearn.metrics import classification_report
warnings.filterwarnings('ignore', category=Warning)


classification_report(Y_test, Y_pred, zero_division=0)
print('Hasil:',classification_report(Y_test,Y_pred))